---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.6.0

platforms:
- name: debian-squeeze
  driver_config:
    box: debian_squeeze_sauspiel
    box_url: http://chef.sauspiel.de/vagrant/virtualbox/debian_squeeze.box

suites:
- name: default
  run_list:
  - recipe[eye_test]

